### ISSUE TITLE
Bitrise: Gradle Wrapper template not found while generating the Gradle Wrapper

### ISSUE THREAD

**Issue by KumMadhu** [bitrise-steplib/steps-generate-gradle-wrapper#1]
+------------------------------------------------------------------------------+

| (4) generate-gradle-wrapper@0.9.2                                            |
+------------------------------------------------------------------------------+
| id: generate-gradle-wrapper                                                  |
| version: 0.9.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-07-17T04:04:50Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[04:04:50] Start installing (golang) with apt-get       
INFO[04:04:50]  * [OK] Step dependency (go) installed, available. 
Configs:
- ProjectRootDir: /bitrise/src
- GradleVersion: 2.14.1
- AndroidHome: /opt/android-sdk-linux
Search for root build.gradle file
root build.gradle path: /bitrise/src/build.gradle
Ensure Android SDK Licenses
android-sdk-license exist
android-sdk-preview-license exist
intel-android-extra-license not exist, generating...
intel-android-extra-license generated
Generate Gradle Wrapper
gradle wrapper template not exists at: /opt/android-sdk-linux/tools/templates/gradle/wrapper
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | generate-gradle-wrapper@0.9.2 (exit code: 1)                  | 3.00 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...b.com/bitrise-steplib/steps-generate-gradle-wrapper/issues |
| Source: https://github.com/bitrise-steplib/steps-generate-gradle-wrapper     |
+---+---------------------------------------------------------------+----------+

**Comment by trapacska** [comment]
Hey @KumMadhu !

Thanks for reporting the issue, we will look into it soon. Just made an internal note to check this. We will notify you here.

thanks 🚀

**Comment by Any2suited66** [comment]
Was this issue ever fixed? I'm experiencing the same issue.

**Comment by LeKangouroo** [comment]
Hi ! Any news on this issue ? I have the same problem with the following stack : Visual Studio for Mac, installed on macOS 10.13 (High Sierra), set to the Stable channel.

**Comment by fehersanyi-bitrise** [comment]
Hello @itadakimas!

Due to the low priority of the task it has not been started yet. I will make a comment on the task to bump the priority level up if possible.

**Comment by jdecode** [comment]
August, 2020 - experiencing same issue.

@fehersanyi-bitrise : Any status update on the fix?

**Comment by nagaperla** [comment]
November, 2020 - Facing the same issue.

**@fehersanyi-bitrise** : Could you please update about the issue?

**Comment by imrekel** [comment]
hey everyone, sorry for the shamefully long delay. The issue has been fixed in https://github.com/bitrise-steplib/steps-generate-gradle-wrapper/releases/tag/0.10.0 - the updated step is available on bitrise.io.
