### ISSUE TITLE
Minimum supported Gradle version is 6.5. Current version is 6.3 - also with Gradle 6.5.1

### ISSUE THREAD

**Issue by dzinek** [bitrise-steplib/steps-generate-gradle-wrapper#4]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? _0.10.1_
- Is the issue reproducible with the latest version? _YES_
- Does the issue happen sporadically, or every time? _EVERY TIME_
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? _YES_

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Bitrise info

- Build URL: https://app.bitrise.io/build/db8b60f2d15d6f57#
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _NO_
- Log: 

<details>
  <pre>
+------------------------------------------------------------------------------+

| (7) generate-gradle-wrapper@0.10                                             |
+------------------------------------------------------------------------------+
| id: generate-gradle-wrapper                                                  |
| version: 0.10.1                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-03-18T12:22:42Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- ProjectRootDir: /bitrise/src
- GradleVersion: 6.5
gradle "wrapper" "--gradle-version" "6.5" failed with error exit status 1: Starting a Gradle Daemon (subsequent builds will be faster)
FAILURE: Build failed with an exception.
* Where:
Build file '/bitrise/src/app/build.gradle' line: 4
* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.5. Current version is 6.3. If using the gradle wrapper, try editing the distributionUrl in /bitrise/src/gradle/wrapper/gradle-wrapper.properties to gradle-6.5-all.zip
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 28s
  </pre>
</details>

### Steps to reproduce

1. I have returned to my project after few months, upgrade dependencies ALSO upgrade Gradle to 6.5
<details>
  <pre>
#Wed Mar 17 21:23:23 CET 2021
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-all.zip

  </pre>
</details>

2. Project has been tested locally, all is green (build, unit and instrumental tests).
3. Push to repo and trigger build with short and long test.
4. Short test passed - there are only build and run unit tests.
5. Long tests failed on `install-missing-android-tools` - it needs to upgrade cache:pull and cache:push steps as well as upgrade Gradle to 6.5.1
6. After it rebuild run further but failed on Gradle Wrapper step (with error pasted above).
7. I have checked all my setting (build.gradle in root and app, gradle-wrapper.properties, etc) - all seems ok, locally also all is green
8. Downgrade `generate-gradle-wrapper` plugin to 0.9.2 fixed the issue - for me is looks like a workaround.

**Comment by ofalvai** [comment]
Hey @dzinek,

If you commit your `gradle-wrapper.properties` and `gradle-wrapper.jar` files to Git, then you can safely remove this step from your workflow. Running any `./gradlew` command will take care of downloading and caching the correct Gradle version.
